### ISSUE TITLE
problem with new rviz plugin

### ISSUE THREAD

**Issue by chasehrdina** [wg-perception/object_recognition_ros#14]
when building the ork_ros package from source I noticed this script:

 86%] Built target object_recognition_msgs_gencpp
[ 87%] [ 88%] Building CXX object object_recognition_ros/src/info_service/CMakeFiles/object_information_server.dir/info_service.cpp.o
Building CXX object tod/src/CMakeFiles/ecto_detection_ectomodule.dir/detection/module.cpp.o
/home/rabbit/ros_ws/ork/src/object_recognition_ros/src/io/MsgAssembler.cpp: In member function ‘int object_recognition_core::MsgAssembler::process(const ecto::tendrils&, const ecto::tendrils&)’:
/home/rabbit/ros_ws/ork/src/object_recognition_ros/src/io/MsgAssembler.cpp:139:52: error: no match for ‘operator=’ in ‘object.object_recognition_msgs::RecognizedObject_<std::allocator<void> >::point_c$
/home/rabbit/ros_ws/ork/src/object_recognition_ros/src/io/MsgAssembler.cpp:139:52: note: candidate is:
/usr/include/c++/4.6/bits/vector.tcc:161:5: note: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = sensor_msgs::PointCloud2_<std::allocator<vo$
/usr/include/c++/4.6/bits/vector.tcc:161:5: note:   no known conversion for argument 1 from ‘const std::vector<boost::shared_ptr<sensor_msgs::PointCloud2_<std::allocator<void> > > >’ to ‘const std::ve$
[ 88%] Building CXX object tod/src/CMakeFiles/ecto_detection_ectomodule.dir/common/adjacency_ransac.cpp.o
Linking CXX executable /home/rabbit/ros_ws/ork/devel/lib/object_recognition_ros/object_information_server
make[2]: *** [object_recognition_ros/src/io/CMakeFiles/io_ros_ectomodule.dir/MsgAssembler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 88%] Building CXX object tod/src/CMakeFiles/ecto_detection_ectomodule.dir/common/maximum_clique.cpp.o

and then the build subsequently fails. Part of my problem was that curl was not installed and is listed as a dependency for the plugin. Maybe add to docs? For the time being I had to install and older release of ork_ros without the new plugin and everything went just fine.

**Comment by vrabaud** [comment]
rosdep instructions were added a long time ago: http://wg-perception.github.io/object_recognition_core/install.html#rosinstall-file
