### ISSUE TITLE
/recognized_object_array with empty objects

### ISSUE THREAD

**Issue by englertpr** [wg-perception/object_recognition_ros#8]
I have a similar problem like http://answers.ros.org/question/71833/having-problems-with-tod-object-detection/

While running 'rosrun object_recognition_core detection -c detection.ros.ork' I get the output:
***Starting object: 0
29 keypoints in 64 matches
done filling
RANSAC done with 19 inliers
RANSAC done with 0 inliers
********************* found 1 poses

But if I output the recognized objects with 'rostopic echo /recognized_object_array' I get always the output with empty objects like
header: 
  seq: 81
  stamp: 
    secs: 1384859690
    nsecs: 437189972
  frame_id: ''
objects: []
cooccurrence: []

My setup is a Kinect over USB on a Ubuntu 13.04, 64bit

**Comment by vrabaud** [comment]
closing if it works for people now.
